/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CatSessions {
  'categoryId' : CategoryId,
  'learnerId' : string,
  'sessions' : Array<NumBuddySession>,
}
export type CategoryId = string;
export interface LearnerProfile {
  'id' : string,
  'name' : string,
  'createdAt' : string,
}
export interface NumBuddySession {
  'categoryId' : CategoryId,
  'total' : bigint,
  'date' : string,
  'difficulty' : string,
  'score' : bigint,
  'learnerId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportSessions' : ActorMethod<[Array<CatSessions>], undefined>,
  'deleteLearnerProfile' : ActorMethod<[string], undefined>,
  'deleteSessionsByLearner' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLearnerProfiles' : ActorMethod<[], Array<LearnerProfile>>,
  'getSessionsByCategory' : ActorMethod<[string], Array<NumBuddySession>>,
  'getSessionsByLearner' : ActorMethod<[string], Array<CatSessions>>,
  'getSessionsByUser' : ActorMethod<[], Array<CatSessions>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAllSessions' : ActorMethod<[Principal], undefined>,
  'removeSessions' : ActorMethod<[string], undefined>,
  'reset' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLearnerProfile' : ActorMethod<[LearnerProfile], undefined>,
  'saveSession' : ActorMethod<[NumBuddySession], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];