/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Text;
export const NumBuddySession = IDL.Record({
  'categoryId' : CategoryId,
  'total' : IDL.Nat,
  'date' : IDL.Text,
  'difficulty' : IDL.Text,
  'score' : IDL.Nat,
  'learnerId' : IDL.Text,
});
export const CatSessions = IDL.Record({
  'categoryId' : CategoryId,
  'learnerId' : IDL.Text,
  'sessions' : IDL.Vec(NumBuddySession),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LearnerProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportSessions' : IDL.Func([IDL.Vec(CatSessions)], [], []),
  'deleteLearnerProfile' : IDL.Func([IDL.Text], [], []),
  'deleteSessionsByLearner' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLearnerProfiles' : IDL.Func([], [IDL.Vec(LearnerProfile)], ['query']),
  'getSessionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NumBuddySession)],
      ['query'],
    ),
  'getSessionsByLearner' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CatSessions)],
      ['query'],
    ),
  'getSessionsByUser' : IDL.Func([], [IDL.Vec(CatSessions)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAllSessions' : IDL.Func([IDL.Principal], [], []),
  'removeSessions' : IDL.Func([IDL.Text], [], []),
  'reset' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLearnerProfile' : IDL.Func([LearnerProfile], [], []),
  'saveSession' : IDL.Func([NumBuddySession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Text;
  const NumBuddySession = IDL.Record({
    'categoryId' : CategoryId,
    'total' : IDL.Nat,
    'date' : IDL.Text,
    'difficulty' : IDL.Text,
    'score' : IDL.Nat,
    'learnerId' : IDL.Text,
  });
  const CatSessions = IDL.Record({
    'categoryId' : CategoryId,
    'learnerId' : IDL.Text,
    'sessions' : IDL.Vec(NumBuddySession),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LearnerProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportSessions' : IDL.Func([IDL.Vec(CatSessions)], [], []),
    'deleteLearnerProfile' : IDL.Func([IDL.Text], [], []),
    'deleteSessionsByLearner' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLearnerProfiles' : IDL.Func([], [IDL.Vec(LearnerProfile)], ['query']),
    'getSessionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NumBuddySession)],
        ['query'],
      ),
    'getSessionsByLearner' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CatSessions)],
        ['query'],
      ),
    'getSessionsByUser' : IDL.Func([], [IDL.Vec(CatSessions)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAllSessions' : IDL.Func([IDL.Principal], [], []),
    'removeSessions' : IDL.Func([IDL.Text], [], []),
    'reset' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLearnerProfile' : IDL.Func([LearnerProfile], [], []),
    'saveSession' : IDL.Func([NumBuddySession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };